name: Build Check

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20-alpine
      options: --user node

    env:
      SKIP_ENV_VALIDATION: "true"
      BASE_URl: "http://localhost:3000" # This is just for build to not fail
      NEXT_TELEMETRY_DISABLED: "1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.13.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: pnpm build
